/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prclient;
import java.util.Date;
import java.util.Properties;
import java.io.*;
import java. util.*;
import javax.swing.*;
import java.awt.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.*;
import javax.mail.internet.*;


/**
 *
 * @author bolan
 */
public class prHomepage extends javax.swing.JFrame {
    
    String emailto;
    String userTo;
    /**
     * Creates new form prHomepage
     */
    public prHomepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        homepageLabel = new javax.swing.JLabel();
        contactusButton = new javax.swing.JButton();
        text2Label = new javax.swing.JLabel();
        textLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        looseweightButton = new javax.swing.JButton();
        mealplanButton = new javax.swing.JButton();
        gainweightButton = new javax.swing.JButton();
        mealplan2Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POWER RANGERS FITNESS, LLC.");
        setPreferredSize(new java.awt.Dimension(850, 750));

        homepageLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        homepageLabel.setForeground(new java.awt.Color(0, 0, 204));
        homepageLabel.setText("POWER RANGERS WORKOUT");

        contactusButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        contactusButton.setText("CONTACT US");
        contactusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusButtonActionPerformed(evt);
            }
        });

        text2Label.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        text2Label.setText("Select a goal");

        textLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textLabel.setText("Get a Personalized Workout Schedule and Meal Plan");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("I WANT TO LOOSE WEIGHT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("I WANT TO GAIN WEIGHT");

        looseweightButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        looseweightButton.setText("Workout Plan");
        looseweightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                looseweightButtonActionPerformed(evt);
            }
        });

        mealplanButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mealplanButton.setText("Meal Plan");
        mealplanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealplanButtonActionPerformed(evt);
            }
        });

        gainweightButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gainweightButton.setText("Workout Plan");
        gainweightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gainweightButtonActionPerformed(evt);
            }
        });

        mealplan2Button.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        mealplan2Button.setText("Meal Plan");
        mealplan2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealplan2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homepageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textLabel)
                        .addGap(218, 218, 218))))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mealplanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mealplan2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(looseweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gainweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(text2Label))
                            .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(homepageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(textLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(text2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gainweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(looseweightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mealplanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mealplan2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void looseweightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_looseweightButtonActionPerformed
        // TODO add your handling code here:
        String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "javatestba@gmail.com";//
        final String password = "@Test1234";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("javatestba@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness - Loose Weight Workout Plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ "<br><br> <b>LOOSE WEIGHT WORKOUT</b><br><br>\n" +
"5 Workouts per week alternate between the 3:<br>\n" +
"Workout 1: <br>\n" +
"9 movements 50 seconds each 20 seconds rest <br>\n" +
"1.Kick Sit<br>\n" +
"2. high knees <br>\n" +
"3. Jumping jacks <br>\n" +
"4. windmills <br>\n" +
"5. high Kick with touch<br>  \n" +
"6. explosive squat with touch <br>\n" +
"7. Table top toe touches <br>\n" +
"8. butt kicks<br>\n" +
"9. curtsy lunges<br>\n" +
" \n" +
"Workout 2: <br>\n" +
"Warm up<br>\n" +
"30 jumping jacks <br>\n" +
"30 body weight squats <br>\n" +
"30 side to side squats <br>\n" +
"30 butt kicks <br>\n" +
"60 seconds each 15 second rest<br>\n" +
"Squat side punches <br>\n" +
"Plank shoulder taps<br>\n" +
"Plank clamshells left <br>\n" +
"Plank clamshells right <br>\n" +
"Tabletop toe touches <br>\n" +
"Hip thrust walkouts <br>\n" +
"Side crab walk with calf raises <br>\n" +
"Plank leg raises<br>\n" +
"Side lunge into deep lunge left  <br>\n" +
"Side lunge into deep lunge right  <br>\n" +
"Superman swimmers <br>\n" +
"Sit up<br>\n" +
"Cool off stretch<br>\n" +
"<br>\n" +
"Workout 3:<br> \n" +
"Go for a walk jog run for 10 mins<br>\n" +
"1min run, 1 min jog, 30 second walk<br><br>\n" +
"Keep going you got this, <br><br>\n" +
"POWER RANGERS FITTNESS, LLC.<BR>\n" +
"\n</b>",
                    "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }

    }//GEN-LAST:event_looseweightButtonActionPerformed

    private void mealplanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealplanButtonActionPerformed
        // TODO add your handling code here:
        String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "javatestba@gmail.com";//
        final String password = "@Test1234";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("javatestba@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness - Loose Weight Meal Plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ "<br><b>LOOSE WEIGHT MEAL PLAN</b><br><br>\n" +
"Good news! No diet needed. Just be mindful of what you are eating. Everything starts in the kitchen<br>\n" +
"In order to loose weight you do have to be in a caloric deficit, but that does not mean you can only<br>\n" +
"Eat salads. Green vegetables are good to incorporate to help with bloating or even try a greens<br> supplement. Eating a boiled egg in the morning for breakfast can help feel you up until lunch<br>\n" +
"And they’re full of protein. Remember creating a healthy relationship with food is important!<br>\n" +
"Don’t deprive yourself of anything. If you want ice cream, eat it! But don’t go get cake after try to<br> incorporate an extra veggie after. Balance is key!<br><br>\n" +
"Happy eating!<br><br>\n" +
"POWER RANGERS FITNESS, LLC. </b>",
                    "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }

    }//GEN-LAST:event_mealplanButtonActionPerformed

    private void gainweightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gainweightButtonActionPerformed
        // TODO add your handling code here:
        String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "javatestba@gmail.com";//
        final String password = "@Test1234";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("javatestba@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness - Gain Weight Workout Plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ " <br><b>GAIN WEIGHT WORKOUT:</b><br><br>\n" +
"5 days-a-week 1hr (2 upper body/ 2 lower body/ 1 full body) add challenging weights <br> <br>\n" +
" \n" +
"Monday- glutes and quads <br>\n" +
"Warm up – 10 min stretch <br>\n" +
"Stair master 5 mins speed 5-8<br>\n" +
"Squats 5x10<br>\n" +
"Bulgarian split squats 3x10<br>\n" +
"Goblet squat 3x10<br>\n" +
"Walking lunges 4x 10 steps <br>\n" +
"Leg press variations 3x10 of each (wide feet & close feet) <br>\n" +
"Step ups hold at top 3x10 each leg<br>\n" +
" \n" +
"Tuesday- Back and Biceps + abs<br><br>\n" +
"Warm up- 10 min stretch <br>\n" +
"Rack pulls 3x10<br>\n" +
"Under grip rows 3x10 <br>\n" +
"Alternating bicep curls 3x10<br>\n" +
"Assisted shin ups 3x 10(or as many as you can do) <br>\n" +
"Push ups 3x10<br>\n" +
"Straight arm lat pulls 3x10<br><br>\n" +
" \n" +
"Abs: <br>\n" +
"3x10<br>\n" +
"Crunches<br>  \n" +
"Knee tucks<br>\n" +
"Heel taps <br>\n" +
"Slow sit ups <br>\n" +
" \n" +
" \n" +
"Wednesday – hamstrings and glutes <br><br>\n" +
"Warm up- 10 min stretch <br>\n" +
"Stair master 5 mins speed 5-8<br>\n" +
"Romanian Dead Lifts 5x10 <br>\n" +
"Kettle bell swings 3x10 <br>\n" +
"Somo squats 3x10 <br>\n" +
"Good mornings 3x10 <br>\n" +
"Hip thrust 5x10<br>\n" +
" \n" +
"Thursday- chest, shoulders, and triceps + abs<br><br>\n" +
"Bench press 3x10 <br>\n" +
"Military press 3x10<br>\n" +
"\n" +
"\n" +
"ITYs 3x10<br>\n" +
"Tricep push down 3x10<br>\n" +
"Underhand tricep push down 3x10<br>\n" +
"Upright row 3x10<br><br>\n" +
"Abs: <br>\n" +
"3x10<br>\n" +
"Crunches<br>  \n" +
"Knee tucks<br>\n" +
"Heel taps <br>\n" +
"Slow sit ups <br>\n" +
" \n" +
" \n" +
"\n" +
"Friday- full body <br><br>\n" +
"This day you pick 5-8 exercises from any day that you want to do or try something fun like yoga, <br> take a walk, dance, go for a run, etc. Just move your body and have fun you earned it! <br><br>\n" +
"Remember progress is not linear, KEEP GOING, <br><br>\n" +
"POWER RANGERS FITNESS, LLC.<br></b>",
                    "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }

    }//GEN-LAST:event_gainweightButtonActionPerformed

    private void mealplan2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealplan2ButtonActionPerformed
        // TODO add your handling code here:
        String userN =JOptionPane.showInputDialog(null,"Confirm name");
        String email =JOptionPane.showInputDialog(null,"Confirm Email");    
        
        final String SSL_FACTORY = "javax.net.ssl.SSLSocketFactory";
// Get a Properties object
        Properties props = System.getProperties();
        props.setProperty("mail.smtp.host", "smtp.gmail.com");
        props.setProperty("mail.smtp.socketFactory.class", SSL_FACTORY);
        props.setProperty("mail.smtp.socketFactory.fallback", "false");
        props.setProperty("mail.smtp.port", "465");//port: 465
        props.setProperty("mail.smtp.socketFactory.port", "465");
        //props.put("mail.smtp.starttls.required", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.ssl.protocols", "TLSv1.2");
        props.put("mail.smtp.auth", "true");
        props.put("mail.debug", "true");
        props.put("mail.store.protocol", "pop3");
        props.put("mail.transport.protocol", "smtp");
        final String username = "javatestba@gmail.com";//
        final String password = "@Test1234";// Change  axlzidcutlgtiilw
        try {
            Session session = Session.getDefaultInstance(props,
                    new Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication(username, password);
                        }
                    });
// -- Create a new message --
            Message msg = new MimeMessage(session);
// -- Set the FROM and TO fields --
            emailto = email;
            userTo = userN;
            
            
            System.out.println("User name: "+userTo);
            System.out.println("Email: "+emailto);
            msg.setFrom(new InternetAddress("javatestba@gmail.com"));
            msg.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(emailto, false));
            msg.setSubject("PR Fitness - Gain Weight Meal Plan");

            msg.setContent("<b> Dear  </b>" + userTo +","+ " <br><b>GAIN WEIGHT MEAL PLAN</b><br>\n" +
"Make sure you eat three times a day <br>\n" +
"You want to incorporate lots of protein, carbs, fruits and vegetables. <br>\n" +
"Get rid of diet culture eat what you want but just try to create a good balance <br>\n" +
"Incorporate chicken, potatoes, oatmeal, peanut butter, quinoa, salmon, postas<br>\n" +
"Protein shakes: protein powder, 1 cup oatmeal, 1 cup ice, 1 cup almond milk, 1 cup fruit, 1 cup <br>\n" +
"peanut butter<br><br>\n" +
"Happy eating!<br><br>\n" +
"POWER RANGERS FITNESS, LLC.</b>",
                    "text/html");
            msg.setSentDate(new Date());
            Transport.send(msg);
            System.out.println("Message sent.");
        } catch (MessagingException eX) {
            System.out.println("Error when mailing, cause: " + eX);
        }
        catch(Exception es){
            
        }

    }//GEN-LAST:event_mealplan2ButtonActionPerformed

    private void contactusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusButtonActionPerformed
        // TODO add your handling code here:
        new prContact().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contactusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contactusButton;
    private javax.swing.JButton gainweightButton;
    private javax.swing.JLabel homepageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton looseweightButton;
    private javax.swing.JButton mealplan2Button;
    private javax.swing.JButton mealplanButton;
    private javax.swing.JLabel text2Label;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
